package com.kmutt.stcp.entity.backup;
// Generated Feb 18, 2016 11:08:21 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CourseTime generated by hbm2java
 */
@Entity
@Table(name = "course_time"
        , catalog = "stcpdb"
)
public class CourseTime implements java.io.Serializable {


    private Integer id;
    private Course course;
    private Date studyTime;
    private Date examTime;
    private Integer status;
    private Integer semester;

    public CourseTime() {
    }


    public CourseTime(Course course) {
        this.course = course;
    }

    public CourseTime(Course course, Date studyTime, Date examTime, Integer status, Integer semester) {
        this.course = course;
        this.studyTime = studyTime;
        this.examTime = examTime;
        this.status = status;
        this.semester = semester;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "course_id", nullable = false)
    public Course getCourse() {
        return this.course;
    }

    public void setCourse(Course course) {
        this.course = course;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "study_time", length = 19)
    public Date getStudyTime() {
        return this.studyTime;
    }

    public void setStudyTime(Date studyTime) {
        this.studyTime = studyTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "exam_time", length = 19)
    public Date getExamTime() {
        return this.examTime;
    }

    public void setExamTime(Date examTime) {
        this.examTime = examTime;
    }


    @Column(name = "status")
    public Integer getStatus() {
        return this.status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }


    @Column(name = "semester")
    public Integer getSemester() {
        return this.semester;
    }

    public void setSemester(Integer semester) {
        this.semester = semester;
    }


}


