package com.kmutt.stcp.entity.backup;

// Generated Feb 18, 2016 11:08:21 PM by Hibernate Tools 4.3.1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * RoleUser generated by hbm2java
 */
@Entity
@Table(name = "role_user", catalog = "stcpdb")
public class RoleUser implements java.io.Serializable {

    private int id;
    private String description;
    private String role;
    private Set<Account> accounts = new HashSet(0);

    public RoleUser() {
    }

    public RoleUser(int id) {
        this.id = id;
    }

    public RoleUser(int id, String desc, String role, Set accounts) {
        this.id = id;
        this.description = description;
        this.role = role;
        this.accounts = accounts;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Column(name = "description", length = 100)
    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Column(name = "role", length = 100)
    public String getRole() {
        return this.role;
    }

    public void setRole(String role) {
        this.role = role;
    }

    @OneToMany(fetch = FetchType.EAGER, mappedBy = "roleUser", cascade = CascadeType.ALL)
    public Set<Account> getAccounts() {
        return this.accounts;
    }

    public void setAccounts(Set<Account> accounts) {
        this.accounts = accounts;
    }

}
