package com.kmutt.stcp.entity;

// Generated Apr 3, 2016 11:22:28 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CoursePlan generated by hbm2java
 */
@Entity
@Table(name = "course_plan", catalog = "stcpdb")
public class CoursePlan implements java.io.Serializable {

	private Integer id;
	private Account account;
	private Subject subject;
	private Integer semesterYear;
	private Integer semesterTerm;
	private Integer status;

	public CoursePlan() {
	}

	public CoursePlan(Account account, Subject subject) {
		this.account = account;
		this.subject = subject;
	}

	public CoursePlan(Account account, Subject subject, Integer semesterYear,
			Integer semesterTerm, Integer status) {
		this.account = account;
		this.subject = subject;
		this.semesterYear = semesterYear;
		this.semesterTerm = semesterTerm;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "account_id", nullable = false)
	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "subject_id", nullable = false)
	public Subject getSubject() {
		return this.subject;
	}

	public void setSubject(Subject subject) {
		this.subject = subject;
	}

	@Column(name = "semester_year")
	public Integer getSemesterYear() {
		return this.semesterYear;
	}

	public void setSemesterYear(Integer semesterYear) {
		this.semesterYear = semesterYear;
	}

	@Column(name = "semester_term")
	public Integer getSemesterTerm() {
		return this.semesterTerm;
	}

	public void setSemesterTerm(Integer semesterTerm) {
		this.semesterTerm = semesterTerm;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

}
