package com.kmutt.stcp.entity;
// Generated Feb 18, 2016 11:08:21 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CoursePlan generated by hbm2java
 */
@Entity
@Table(name="course_plan"
    ,catalog="stcpdb"
)
public class CoursePlan  implements java.io.Serializable {


     private Integer id;
     private Account account;
     private Course course;
     private Integer semester;
     private Integer status;

    public CoursePlan() {
    }

	
    public CoursePlan(Account account, Course course) {
        this.account = account;
        this.course = course;
    }
    public CoursePlan(Account account, Course course, Integer semester, Integer status) {
       this.account = account;
       this.course = course;
       this.semester = semester;
       this.status = status;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="account_id", nullable=false)
    public Account getAccount() {
        return this.account;
    }
    
    public void setAccount(Account account) {
        this.account = account;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="course_id", nullable=false)
    public Course getCourse() {
        return this.course;
    }
    
    public void setCourse(Course course) {
        this.course = course;
    }

    
    @Column(name="semester")
    public Integer getSemester() {
        return this.semester;
    }
    
    public void setSemester(Integer semester) {
        this.semester = semester;
    }

    
    @Column(name="status")
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }




}


