package com.kmutt.stcp.entity;
// Generated Feb 18, 2016 11:08:21 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Curriculum generated by hbm2java
 */
@Entity
@Table(name = "curriculum"
        , catalog = "stcpdb"
)
public class Curriculum implements java.io.Serializable {


    private Integer id;
    private String name;
    private String startedYear;
    private Integer accId;
    private String startYear;
    private Set<CourseCurriculum> courseCurriculums = new HashSet(0);

    public Curriculum() {
    }

    public Curriculum(String name, String startedYear, Integer accId, String startYear, Set courseCurriculums) {
        this.name = name;
        this.startedYear = startedYear;
        this.accId = accId;
        this.startYear = startYear;
        this.courseCurriculums = courseCurriculums;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)


    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }


    @Column(name = "name", length = 45)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }


    @Column(name = "started_year", length = 45)
    public String getStartedYear() {
        return this.startedYear;
    }

    public void setStartedYear(String startedYear) {
        this.startedYear = startedYear;
    }


    @Column(name = "acc_id")
    public Integer getAccId() {
        return this.accId;
    }

    public void setAccId(Integer accId) {
        this.accId = accId;
    }


    @Column(name = "start_year", length = 45)
    public String getStartYear() {
        return this.startYear;
    }

    public void setStartYear(String startYear) {
        this.startYear = startYear;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "curriculum")
    public Set<CourseCurriculum> getCourseCurriculums() {
        return this.courseCurriculums;
    }

    public void setCourseCurriculums(Set<CourseCurriculum> courseCurriculums) {
        this.courseCurriculums = courseCurriculums;
    }


}


