package com.kmutt.stcp.entity;

// Generated Apr 3, 2016 11:22:28 AM by Hibernate Tools 4.3.1

import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Prerequisite generated by hbm2java
 */
@Entity
@Table(name = "prerequisite", catalog = "stcpdb")
public class Prerequisite implements java.io.Serializable {

	private int id;
	private Subject subjectBySubjectId;
	private Subject subjectByPresubjectId;

	public Prerequisite() {
	}

	public Prerequisite(int id) {
		this.id = id;
	}

	public Prerequisite(int id, Subject subjectBySubjectId,
			Subject subjectByPresubjectId) {
		this.id = id;
		this.subjectBySubjectId = subjectBySubjectId;
		this.subjectByPresubjectId = subjectByPresubjectId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "subject_id")
	public Subject getSubjectBySubjectId() {
		return this.subjectBySubjectId;
	}

	public void setSubjectBySubjectId(Subject subjectBySubjectId) {
		this.subjectBySubjectId = subjectBySubjectId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "presubject_id")
	public Subject getSubjectByPresubjectId() {
		return this.subjectByPresubjectId;
	}

	public void setSubjectByPresubjectId(Subject subjectByPresubjectId) {
		this.subjectByPresubjectId = subjectByPresubjectId;
	}

}
