package com.kmutt.stcp.entity;
// Generated Apr 2, 2016 6:17:49 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * RoleUser generated by hbm2java
 */
@Entity
@Table(name = "role_user"
        , catalog = "stcpdb"
)
public class RoleUser implements java.io.Serializable {


    private Integer id;
    private String description;
    private String role;
    private Set accounts = new HashSet(0);

    public RoleUser() {
    }

    public RoleUser(String description, String role, Set accounts) {
        this.description = description;
        this.role = role;
        this.accounts = accounts;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }


    @Column(name = "description", length = 100)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }


    @Column(name = "role", length = 100)
    public String getRole() {
        return this.role;
    }

    public void setRole(String role) {
        this.role = role;
    }

    @OneToMany(fetch = FetchType.EAGER, mappedBy = "roleUser", cascade = CascadeType.ALL)
    public Set getAccounts() {
        return this.accounts;
    }

    public void setAccounts(Set accounts) {
        this.accounts = accounts;
    }


}


