package com.kmutt.stcp.entity;
// Generated Feb 18, 2016 11:08:21 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * RoleUser generated by hbm2java
 */
@Entity
@Table(name="role_user"
    ,catalog="stcpdb"
)
public class RoleUser  implements java.io.Serializable {


     private int id;
     private String desc;
     private String role;
     private Set accounts = new HashSet(0);

    public RoleUser() {
    }

	
    public RoleUser(int id) {
        this.id = id;
    }
    public RoleUser(int id, String desc, String role, Set accounts) {
       this.id = id;
       this.desc = desc;
       this.role = role;
       this.accounts = accounts;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="desc", length=100)
    public String getDesc() {
        return this.desc;
    }
    
    public void setDesc(String desc) {
        this.desc = desc;
    }

    
    @Column(name="role", length=100)
    public String getRole() {
        return this.role;
    }
    
    public void setRole(String role) {
        this.role = role;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="roleUser")
    public Set getAccounts() {
        return this.accounts;
    }
    
    public void setAccounts(Set accounts) {
        this.accounts = accounts;
    }




}


