package com.kmutt.stcp.entity;

// Generated Apr 3, 2016 11:22:28 AM by Hibernate Tools 4.3.1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.*;

import java.util.HashSet;
import java.util.Set;

/**
 * RoleUser generated by hbm2java
 */
@Entity
@Table(name = "role_user", catalog = "stcpdb")
public class RoleUser implements java.io.Serializable {

	private Integer id;
	private String description;
	private String role;
	private Set<Account> accounts = new HashSet(0);

	public RoleUser() {
	}

	public RoleUser(int id) {
		this.id = id;
	}

	public RoleUser(int id, String description, String role, Set accounts) {
		this.id = id;
		this.description = description;
		this.role = role;
		this.accounts = accounts;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "description", length = 100)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "role", length = 100)
	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "roleUser", cascade = CascadeType.ALL)
	public Set<Account> getAccounts() {
		return this.accounts;
	}

	public void setAccounts(Set<Account> accounts) {
		this.accounts = accounts;
	}

}
