package com.kmutt.stcp.entity;

// Generated Apr 3, 2016 11:22:28 AM by Hibernate Tools 4.3.1

import javax.persistence.*;

import java.util.HashSet;
import java.util.Set;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Subject generated by hbm2java
 */
@Entity
@Table(name = "subject", catalog = "stcpdb")
public class Subject implements java.io.Serializable {

	private Integer id;
	private String subjectCode;
	private String nameThai;
	private String nameEng;
	private String subjectType;
	private String credit;
	private Integer status;
	private String detailThai;
	private String detailEng;
	private Set<Course> courses = new HashSet(0);
	private Set<Prerequisite> prerequisitesForSubjectId = new HashSet(0);
	private Set<Prerequisite> prerequisitesForPresubjectId = new HashSet(0);
	private Set<CurriculumSubject> curriculumSubjects = new HashSet(0);
	private Set<CoursePlan> coursePlans = new HashSet(0);

	public Subject() {
	}

	public Subject(String subjectCode, String nameThai, String nameEng,
			String subjectType, String credit, Integer status,
			String detailThai, String detailEng, Set courses,
			Set prerequisitesForSubjectId, Set prerequisitesForPresubjectId,
			Set curriculumSubjects, Set coursePlans) {
		this.subjectCode = subjectCode;
		this.nameThai = nameThai;
		this.nameEng = nameEng;
		this.subjectType = subjectType;
		this.credit = credit;
		this.status = status;
		this.detailThai = detailThai;
		this.detailEng = detailEng;
		this.courses = courses;
		this.prerequisitesForSubjectId = prerequisitesForSubjectId;
		this.prerequisitesForPresubjectId = prerequisitesForPresubjectId;
		this.curriculumSubjects = curriculumSubjects;
		this.coursePlans = coursePlans;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "subject_code", length = 255)
	public String getSubjectCode() {
		return this.subjectCode;
	}

	public void setSubjectCode(String subjectCode) {
		this.subjectCode = subjectCode;
	}

	@Column(name = "name_thai")
	public String getNameThai() {
		return this.nameThai;
	}

	public void setNameThai(String nameThai) {
		this.nameThai = nameThai;
	}

	@Column(name = "name_eng")
	public String getNameEng() {
		return this.nameEng;
	}

	public void setNameEng(String nameEng) {
		this.nameEng = nameEng;
	}

	@Column(name = "subject_type", length = 255)
	public String getSubjectType() {
		return this.subjectType;
	}

	public void setSubjectType(String subjectType) {
		this.subjectType = subjectType;
	}

	@Column(name = "credit", length = 45)
	public String getCredit() {
		return this.credit;
	}

	public void setCredit(String credit) {
		this.credit = credit;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Column(name = "detail_thai",  columnDefinition="TEXT")
	public String getDetailThai() {
		return this.detailThai;
	}

	public void setDetailThai(String detailThai) {
		this.detailThai = detailThai;
	}

	@Column(name = "detail_eng", columnDefinition="TEXT")
	public String getDetailEng() {
		return this.detailEng;
	}

	public void setDetailEng(String detailEng) {
		this.detailEng = detailEng;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "subject", cascade = CascadeType.ALL)
	public Set<Course> getCourses() {
		return this.courses;
	}

	public void setCourses(Set<Course> courses) {
		this.courses = courses;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "subjectBySubjectId", cascade = CascadeType.ALL)
	public Set<Prerequisite> getPrerequisitesForSubjectId() {
		return this.prerequisitesForSubjectId;
	}

	public void setPrerequisitesForSubjectId(
			Set<Prerequisite> prerequisitesForSubjectId) {
		this.prerequisitesForSubjectId = prerequisitesForSubjectId;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "subjectByPresubjectId", cascade = CascadeType.ALL)
	public Set<Prerequisite> getPrerequisitesForPresubjectId() {
		return this.prerequisitesForPresubjectId;
	}

	public void setPrerequisitesForPresubjectId(
			Set<Prerequisite> prerequisitesForPresubjectId) {
		this.prerequisitesForPresubjectId = prerequisitesForPresubjectId;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "subject", cascade = CascadeType.ALL)
	public Set<CurriculumSubject> getCurriculumSubjects() {
		return this.curriculumSubjects;
	}

	public void setCurriculumSubjects(Set<CurriculumSubject> curriculumSubjects) {
		this.curriculumSubjects = curriculumSubjects;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "subject", cascade = CascadeType.ALL)
	public Set<CoursePlan> getCoursePlans() {
		return this.coursePlans;
	}

	public void setCoursePlans(Set<CoursePlan> coursePlans) {
		this.coursePlans = coursePlans;
	}

}
