package com.kmutt.stcp.entity;
// Generated Apr 2, 2016 6:17:49 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user"
        , catalog = "stcpdb"
)
public class User implements java.io.Serializable {


    private Integer id;
    private String address;
    private Date birthday;
    private String citizenId;
    private String email;
    private String faculty;
    private String firstname;
    private Integer gender;
    private String lastname;
    private String major;
    private String mobile;
    private int semester;
    private String studyProgram;
    private Set accounts = new HashSet(0);

    public User() {
    }


    public User(String citizenId, String email, String faculty, String firstname, String lastname, String major, int semester, String studyProgram) {
        this.citizenId = citizenId;
        this.email = email;
        this.faculty = faculty;
        this.firstname = firstname;
        this.lastname = lastname;
        this.major = major;
        this.semester = semester;
        this.studyProgram = studyProgram;
    }

    public User(String address, Date birthday, String citizenId, String email, String faculty, String firstname, Integer gender, String lastname, String major, String mobile, int semester, String studyProgram, Set accounts) {
        this.address = address;
        this.birthday = birthday;
        this.citizenId = citizenId;
        this.email = email;
        this.faculty = faculty;
        this.firstname = firstname;
        this.gender = gender;
        this.lastname = lastname;
        this.major = major;
        this.mobile = mobile;
        this.semester = semester;
        this.studyProgram = studyProgram;
        this.accounts = accounts;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }


    @Column(name = "address")
    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "birthday", length = 19)
    public Date getBirthday() {
        return this.birthday;
    }

    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }


    @Column(name = "citizen_id", nullable = false, length = 20)
    public String getCitizenId() {
        return this.citizenId;
    }

    public void setCitizenId(String citizenId) {
        this.citizenId = citizenId;
    }


    @Column(name = "email", nullable = false, length = 100)
    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }


    @Column(name = "faculty", nullable = false, length = 100)
    public String getFaculty() {
        return this.faculty;
    }

    public void setFaculty(String faculty) {
        this.faculty = faculty;
    }


    @Column(name = "firstname", nullable = false, length = 45)
    public String getFirstname() {
        return this.firstname;
    }

    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }


    @Column(name = "gender")
    public Integer getGender() {
        return this.gender;
    }

    public void setGender(Integer gender) {
        this.gender = gender;
    }


    @Column(name = "lastname", nullable = false, length = 45)
    public String getLastname() {
        return this.lastname;
    }

    public void setLastname(String lastname) {
        this.lastname = lastname;
    }


    @Column(name = "major", nullable = false, length = 100)
    public String getMajor() {
        return this.major;
    }

    public void setMajor(String major) {
        this.major = major;
    }


    @Column(name = "mobile", length = 20)
    public String getMobile() {
        return this.mobile;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }


    @Column(name = "semester", nullable = false)
    public int getSemester() {
        return this.semester;
    }

    public void setSemester(int semester) {
        this.semester = semester;
    }


    @Column(name = "study_program", nullable = false, length = 100)
    public String getStudyProgram() {
        return this.studyProgram;
    }

    public void setStudyProgram(String studyProgram) {
        this.studyProgram = studyProgram;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "user", cascade = CascadeType.ALL)
    public Set getAccounts() {
        return this.accounts;
    }

    public void setAccounts(Set accounts) {
        this.accounts = accounts;
    }


}


