-- MySQL Script generated by MySQL Workbench
-- Fri Feb 12 01:44:29 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema stcpdb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `stcpdb` ;

-- -----------------------------------------------------
-- Schema stcpdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `stcpdb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema stcpdb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `stcpdb` ;

-- -----------------------------------------------------
-- Schema stcpdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `stcpdb` DEFAULT CHARACTER SET utf8 ;
USE `stcpdb` ;

-- -----------------------------------------------------
-- Table `stcpdb`.`role_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stcpdb`.`role_user` ;

CREATE TABLE IF NOT EXISTS `stcpdb`.`role_user` (
  `id` INT NOT NULL,
  `desc` VARCHAR(100) NULL,
  `role` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stcpdb`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stcpdb`.`user` ;

CREATE TABLE IF NOT EXISTS `stcpdb`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `gender` INT NULL,
  `address` VARCHAR(255) NULL,
  `email` VARCHAR(100) NOT NULL,
  `birthday` DATETIME NULL,
  `mobile` VARCHAR(20) NULL,
  `citizen_id` VARCHAR(20) NOT NULL,
  `semester` INT NOT NULL,
  `study_program` VARCHAR(100) NOT NULL,
  `faculty` VARCHAR(100) NOT NULL,
  `major` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stcpdb`.`account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stcpdb`.`account` ;

CREATE TABLE IF NOT EXISTS `stcpdb`.`account` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `role_user_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`, `user_id`),
  INDEX `fk_account_role_user_idx` (`role_user_id` ASC),
  INDEX `fk_account_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_account_role_user`
    FOREIGN KEY (`role_user_id`)
    REFERENCES `stcpdb`.`role_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_account_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `stcpdb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stcpdb`.`course`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stcpdb`.`course` ;

CREATE TABLE IF NOT EXISTS `stcpdb`.`course` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  `min_student` INT NOT NULL,
  `max_student` INT NOT NULL,
  `detail` VARCHAR(255) NULL,
  `credit` INT NOT NULL,
  `status` INT NOT NULL,
  `type` INT NOT NULL,
  `course_id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stcpdb`.`curriculum`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stcpdb`.`curriculum` ;

CREATE TABLE IF NOT EXISTS `stcpdb`.`curriculum` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `started_year` VARCHAR(45) NULL,
  `acc_id` INT NULL,
  `start_year` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stcpdb`.`course_curriculum`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stcpdb`.`course_curriculum` ;

CREATE TABLE IF NOT EXISTS `stcpdb`.`course_curriculum` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `course_id` INT NOT NULL,
  `curriculum_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_course_curriculum_course1_idx` (`course_id` ASC),
  INDEX `fk_course_curriculum_curriculum1_idx` (`curriculum_id` ASC),
  CONSTRAINT `fk_course_curriculum_course1`
    FOREIGN KEY (`course_id`)
    REFERENCES `stcpdb`.`course` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_course_curriculum_curriculum1`
    FOREIGN KEY (`curriculum_id`)
    REFERENCES `stcpdb`.`curriculum` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stcpdb`.`course_lecture`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stcpdb`.`course_lecture` ;

CREATE TABLE IF NOT EXISTS `stcpdb`.`course_lecture` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `account_id` INT NOT NULL,
  `course_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_course_lecture_account1_idx` (`account_id` ASC),
  INDEX `fk_course_lecture_course1_idx` (`course_id` ASC),
  CONSTRAINT `fk_course_lecture_account1`
    FOREIGN KEY (`account_id`)
    REFERENCES `stcpdb`.`account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_course_lecture_course1`
    FOREIGN KEY (`course_id`)
    REFERENCES `stcpdb`.`course` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stcpdb`.`course_plan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stcpdb`.`course_plan` ;

CREATE TABLE IF NOT EXISTS `stcpdb`.`course_plan` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `semester` INT NULL,
  `status` INT NULL,
  `account_id` INT NOT NULL,
  `course_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_course_plan_account1_idx` (`account_id` ASC),
  INDEX `fk_course_plan_course1_idx` (`course_id` ASC),
  CONSTRAINT `fk_course_plan_account1`
    FOREIGN KEY (`account_id`)
    REFERENCES `stcpdb`.`account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_course_plan_course1`
    FOREIGN KEY (`course_id`)
    REFERENCES `stcpdb`.`course` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stcpdb`.`course_time`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stcpdb`.`course_time` ;

CREATE TABLE IF NOT EXISTS `stcpdb`.`course_time` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `study_time` DATETIME NULL,
  `exam_time` DATETIME NULL,
  `status` INT NULL,
  `semester` INT NULL,
  `course_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_course_time_course1_idx` (`course_id` ASC),
  CONSTRAINT `fk_course_time_course1`
    FOREIGN KEY (`course_id`)
    REFERENCES `stcpdb`.`course` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `stcpdb` ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
